Commands Rewrite
vinhowe/Hound pull request #4
Opened 2021-03-28 15:40 UTC by Sxtanna

This PR contains rewrites of the commands using ACF

2021-03-28 15:40 UTC, Sxtanna commented
WIP btw

2021-03-29 22:22 UTC, vinhowe requested changes
Mostly just whitespace but I had a few questions too. Let me know if I missed anything you wanted me to look at.

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/Hound.kt
> +
```suggestion
```

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/Hound.kt
> +        }
It feels to me like there are an awful lot of linebreaks here.

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/cmds/BlockSearchCommand.kt
> +
Again, there are a lot of empty lines here. It just feels weird I guess.

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/cmds/ChestSearchCommand.kt
> +
```suggestion
```

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/cmds/ChestSearchCommand.kt
> +
```suggestion
    private fun String.plural(count: Int, suffix: String) = if (count == 1) this else "$this$suffix"
```

Some inconsistent 2 line breaks. Correct me if this is a Kotlin convention or something.

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/cmds/ChestSearchCommand.kt
> +
```suggestion
```

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/cmds/ChestSearchCommand.kt
> +    }
These both look fantastic. A big improvement.

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/cmds/LiveChestSearchCommand.kt
> +}
```suggestion
        }
    }
}
```

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/cmds/LiveChestSearchCommand.kt
> +
```suggestion
```

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/cmds/TargetCommand.kt
> +
```suggestion
        if (x == null || z == null) {
            hound.clearGuideForPlayer(player)
        } else {
            hound.createGuideForPlayer(player, x, z)
        }
```

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/cmds/TorchGuideCommand.kt
> +
```suggestion
        if (spacing == null) {
            hound.clearStaticHighlightsForPlayer(player)
        } else {
            hound.createTorchHighlightsForPlayer(player, spacing)
        }
```

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/cmds/BlockSearchCommand.kt
> +package cmds
Could we go with either `commands` or `command` for the package name, depending on convention? This feels unnecessarily succinct.

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/Hound.kt
> +        }
These completions make the command feel a lot more like a built-in command (like `tp`). Good job.

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/cmds/LiveChestSearchCommand.kt
> +        }
I might be missing something here, but why can't you throw a command error in Hound.kit in `registerIssuerAwareContext(LiveSearchState::class.java)` if current state == desired state?

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/cmds/LiveChestSearchCommand.kt
> +
```suggestion
```

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/cmds/LiveChestSearchCommand.kt
> +
```suggestion
```

2021-03-29 22:22 UTC, vinhowe commented on src/main/kotlin/cmds/ChestSearchCommand.kt
> +
```suggestion
```

2021-03-29 23:38 UTC, vinhowe approved these changes
LGTM

2021-03-29 23:38 UTC, merged