Create README.md
vinhowe/Hound pull request #8
Opened 2021-04-07 19:53 UTC by VasilisThePikachu

Pretty basic but oh well at least I tried

Request as many changes as you want

2021-04-07 20:55 UTC, vinhowe requested changes
Thanks for this! I had a few notes.

2021-04-07 20:55 UTC, vinhowe commented on README.md
> +Hound is licensed under the [MIT License](https://github.com/vinhowe/Hound/blob/main/LICENSE)
Just changed to GPLv3 (e46dc136951c5259ce8377add67a7aa101057049)

2021-04-07 20:55 UTC, vinhowe commented on README.md
> +5: Copy the compiled Hound jar from ```\build\libs```
Could we get all of the Windows clone/build steps in a code block of shell commands? A good example of this is [Signal Desktop's contributing guidelines](https://github.com/signalapp/Signal-Desktop/blob/master/CONTRIBUTING.md#all-platforms).

I think everything from cloning to building can be done in Git Bash and WSL, but I haven't tested on Windows.

---

Also as a side note, Markdown supports nicely formatted ordered lists:

```md
1. a
1. b
1. c
```

becomes:

1. a
2. b
3. c

2021-04-07 20:55 UTC, vinhowe commented on README.md
> +* Navigate to a coordinate.
```suggestion
* Navigate to coordinates.
```

2021-04-07 20:55 UTC, vinhowe commented on README.md
> +Hound is a Spigot Plugin that adds useful navigation and search features to your server using glowing Shulker bullets.
```suggestion
Hound is a Spigot plugin that adds useful navigation and search features using glowing Shulker bullets.
```

We have 3 entity types set up internally to use as highlights, so this will change eventually, but I think it's fine to specifically single out Shulker bullets for now.

2021-04-07 20:55 UTC, vinhowe commented on README.md
> +
```suggestion
```

We should hold off on this section until we actually roll a release.

2021-04-08 13:05 UTC, VasilisThePikachu reviewed
Thank you for your suggestions! I applied the changes

2021-04-08 19:48 UTC, vinhowe requested changes
Just a few nitpicks but otherwise looking good!

2021-04-08 19:48 UTC, vinhowe commented on README.md
> +1. Install ```git``` using your package manager
```suggestion
1. Install `git` using your package manager
```

2021-04-08 19:48 UTC, vinhowe commented on README.md
> +Now run these commands in your terminal
```suggestion
Now run these commands in your terminal:
```

2021-04-08 19:48 UTC, vinhowe commented on README.md
> +Your build should be in ```/build/libs```
```suggestion
Your build should be in `/build/libs`.
```

2021-04-08 19:48 UTC, vinhowe commented on README.md
> +Hound is licensed under the [GPLv3 License](https://github.com/vinhowe/Hound/blob/main/LICENSE)
```suggestion
Hound is licensed under the [GPLv3 License](https://github.com/vinhowe/Hound/blob/main/LICENSE).
```

2021-04-08 21:22 UTC, vinhowe approved these changes
Thanks again Vasilis!

2021-04-08 21:22 UTC, merged

2021-04-08 21:26 UTC, VasilisThePikachu commented
Thanks! Even though it's not much I wanted to help